### ISSUE TITLE
It's done when the /api/add-movie route successfully adds a movie when tested using Insomnia.

### ISSUE THREAD

**Issue by KarenHarley** [KarenHarley/Movie-Database#4]

**Comment by jhernandez50** [comment]
// POST Route for a new movie
app.post('/api/add-movie', (req, res) => {
  console.info(`${req.method} request received to add a movie`);

  const { name } = req.body;

  if (req.body) {
    const newMovie = {
      name,
    };

    readAndAppend(newMovie, ‘./api/add-movie.json');
    res.json(`Movie added successfully `);
  } else {
    res.error('Error in adding a ‘movie);
  }
});
